# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c00da00c937ccd1963555ae237d793eb94d3baee82e01fc3ccae3bf436e6e86609a43ca076b878e677ecea82ed4659076dbffbc89a0929e2b5af8a9288fa962b

test:
  secret_key_base: 130b785b1e280d89d5e49d145f12f92d9055d1780468fccabad2532233c947aaf8a4516089112b9e9bd7edc886054d3059bf4a46ed19c2d9a58e46af9207d272

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
